### ISSUE TITLE
Test using bitwise operations on arbitrary width integers

### ISSUE THREAD

**Issue by hackedy** [verified-network-toolchain/petr4#132]
I guess this is a bad test, although none of the expressions involve negative numbers: `examples/checker_tests/good/constant_folding.p4`

**Comment by stp59** [comment]
Why is this a bad test? It seems to me like the spec allows this?

**Comment by hackedy** [comment]
"8.9.3. Illegal arithmetic expressions" says something like `32w5 & 3` is okay but `5 & 3` isn't okay.
