### ISSUE TITLE
Compatibility with Cygwin

### ISSUE THREAD

**Issue by QinshiWang** [verified-network-toolchain/petr4#237]
### Motivation
I am trying to install Petr4 on Cygwin with OPAM, which is my usual toolchain for OCaml and Coq.
### Detail
Petr4 and P4PP depend on a package called `core`[1]. `core` is not compatible with Cygwin, because some of the POSIX APIs are not implemented in Cygwin. `core` has a subset called `core_kernel`[2], which is compatible with Cygwin. I find Petr4 and P4PP mainly use `core_kernal` and only depend on `core` at a few positions in wrappers, e.g. [3-5]. In [3, 4], `core` is only used when executing the command, so it might be easier to make it compatible. It is more complicated for [5]. Is it hard to get around of `core`?

[1] github.com/janestreet/core
[2] github.com/janestreet/core_kernel
[3] https://github.com/cornell-netlab/petr4/blob/master/bin/main.ml#L118
[4] https://github.com/cornell-netlab/p4pp/blob/master/bin/main.ml#L50
[5] https://github.com/cornell-netlab/petr4/blob/master/test/test.ml#L1

**Comment by jnfoster** [comment]
Thanks for the interest in Petr4! 

We have a variant of the implementation that runs in a browser using the Bucklescript OCaml to JS compiler. So I think we should be able to detangle `core` and only rely on `core_kernel`. Let me investigate...

**Comment by jnfoster** [comment]
In the short-term would a Linux-based VM be workable for you?

**Comment by QinshiWang** [comment]
@jnfoster Thanks for your following up. Yes, I can use [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).
