### ISSUE TITLE
CI failed mysteriously

### ISSUE THREAD

**Issue by QinshiWang** [verified-network-toolchain/petr4#307]
I tried it twice, but all fails when installing some package.
https://github.com/verified-network-toolchain/petr4/actions/runs/1625572751

**Comment by jnfoster** [comment]
Those are core OCaml / Jane Street packages.

Let's see if the issue persists? It doesn't seem to be anything in our scripts and may well be transient.

**Comment by QinshiWang** [comment]
Still, it goes in an unpredictable way. https://github.com/verified-network-toolchain/petr4/actions/runs/1641999336

**Comment by pataei** [comment]
Sorry, I just saw this. I look into this today to make sure the script is
set up correctly.

-Parisa

**Comment by QinshiWang** [comment]
It may be not necessarily something's wrong, but because some sources are unstable.

**Comment by pataei** [comment]
Yeah, menhir had a new release and it seems that its parser has some
errors. I forced the current actions to use the previous release of it for
now. Petr4-build action was successful (it had the same issue as
poulet4-build action), once poulet4-build action passes successfully on my
fork I'll push my changes.

**Comment by hackedy** [comment]
Fixed in #323.
