### ISSUE TITLE
why are error and match_kind types categorized as base types in P4?

### ISSUE THREAD

**Issue by pataei** [verified-network-toolchain/petr4#386]
P4 spec categories `error` and `match_kind` types as `baseType`, however, they both have to be declared by a P4 program. Here is the grammar for `baseType` and `declaration`:

```
baseType
    : BOOL
    | ERROR
    | MATCH_KIND
    | STRING
    | INT
    | BIT
    | BIT '<' INTEGER '>'
    | INT '<' INTEGER '>'
    | VARBIT '<' INTEGER '>'
    | BIT '<' '(' expression ')' '>'
    | INT '<' '(' expression ')' '>'
    | VARBIT '<' '(' expression ')' '>'
    ;

declaration
    : constantDeclaration
    | externDeclaration
    | actionDeclaration
    | parserDeclaration
    | typeDeclaration
    | controlDeclaration
    | instantiation
    | errorDeclaration
    | matchKindDeclaration
    | functionDeclaration
    ;

errorDeclaration
    : ERROR '{' identifierList '}'
    ;

matchKindDeclaration
    : MATCH_KIND '{' identifierList '}'
    ;

identifierList
    : name
    | identifierList ',' name
    ;
```

A quick look through P4 spec and where these types are used resulted only in one example which uses `error` type in arguments:

```
extern void verify(in bool condition, in error err);

ParserModel.verify(bool condition, error err) {
    if (condition == false) {
        ParserModel.parserError = err;
        goto reject;
    }
}
```

@jnfoster and @hackedy Any other examples of using these types where `baseType` is used?

**Comment by hackedy** [comment]
I don't think the error type has to be declared. But members of the error type do need to be declared. It's like error exists but new members can be added to it by `error {member1; member2 }` declarations. Likewise for match_kind.

**Comment by hackedy** [comment]
Also where I usually see `error` used is as a field of the `standard_metadata_t` struct in V1Model. I don't know if that's the kind of use you're looking for though?

**Comment by pataei** [comment]
Yeah, `error` itself doesn't have to be declared but its member does. And yes, `standard_metadata_t` is a great example. Thx Ryan!

**Comment by hackedy** [comment]
yw!

**Comment by jnfoster** [comment]
In the same vein, you can also declare variables of type `match_kind` or `error`. Not incredibly useful, but legal.
