### ISSUE TITLE
Casts of function calls associated backwards

### ISSUE THREAD

**Issue by hackedy** [verified-network-toolchain/petr4#69]
See `examples/checker_tests/cast-call.p4` for an example. If you write (T)f(x) it gets parsed as ((T) f)  (x), which then gets rejected by the typechecker.

**Comment by jnfoster** [comment]
I think `p4c` has the same bug.

https://github.com/p4lang/p4c/blob/master/frontends/parsers/p4/p4parser.ypp#L1362

**Comment by hackedy** [comment]
Yes, it looks like p4c rejects cast-call.p4. Maybe it belongs in the checker_tests/bad folder, then?

**Comment by jnfoster** [comment]
This just got fixed with another lexer hack for `p4c`. Let's keep it here, I'll do the same ugliness and then we'll handle this one too.

**Comment by aaglenn** [comment]
> This just got fixed with another lexer hack for p4c.

git blame doesn't point me to a likely change for this; nor was I able to find a PR regarding the change anywhere in p4lang/p4c. I just ran into this error on 'make test' with the latest p4pp/petr4

**Comment by jnfoster** [comment]
Hmm. I'll take another look...

**Comment by hackedy** [comment]
I am halfway through a lexer hack fix for this.
